### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by devinrhode2** [tj/better-assert#13]
I'm using babel as a part of ember-cli, had to use ember-browserify to be able to import better-assert, but now I get `fs.readFileSync is not a function` because this is a browser, of course.

This code:
```javascript
import assert from 'npm:better-assert'

try {
	console.log('before calling assert')
	assert('true')
	console.log('called assert')
	assert(false)
	console.log('called with false')
} catch (e) {
	console.log('caught err'+e.stack)
}
```
Prints this:
```
before calling assert
cat.js:7 called assert
cat.js:11 caught errTypeError: fs.readFileSync is not a function
    at assert (http://localhost:4200/assets/vendor.js:65236:16)
    at Module.callback (http://localhost:4200/assets/dynamic-segments.js:385:35)
    at Module.exports (http://localhost:4200/assets/vendor.js:131:32)
    at requireModule (http://localhost:4200/assets/vendor.js:30:18)
    at Class._extractDefaultExport (http://localhost:4200/assets/vendor.js:144697:20)
    at Class.resolveOther (http://localhost:4200/assets/vendor.js:144432:32)
    at Class.superWrapper (http://localhost:4200/assets/vendor.js:35482:22)
    at Class.resolve (http://localhost:4200/assets/vendor.js:16205:43)
    at resolve (http://localhost:4200/assets/vendor.js:12565:36)
    at Object.resolve (http://localhost:4200/assets/vendor.js:12025:21)
```

Ember goliath generates horrible stack trace! :100: :)

Going to fork and see what I can do..!

**Comment by devinrhode2** [comment]
This issue: https://github.com/tj/better-assert/issues/12 COULD ALSO affect the ember/babel/browser use case, but I'm NOT SURE.

**Comment by devinrhode2** [comment]
I replaced the fs.readFile call with a window.fetch call for the browser, and am going to leave this as a separate fork here: https://github.com/devinrhode2/better-assert-browser
