### ISSUE TITLE
Error when importing using a different name than "assert"

### ISSUE THREAD

**Issue by thevtm** [tj/better-assert#18]
Basically if you name the assert function other than "assert" the regex fails.
```javascript
const betterAss = require("./index");
betterAss(1 === 2);
```
```
~/better-assert/index.js:30
  var src = line.match(/assert\((.*)\)/)[1];
                                        ^

TypeError: Cannot read property '1' of null
    at assert (~/better-assert/index.js:30:41)
    at Object.<anonymous> (~/better-assert/fn-name-test.js:4:1)
```

**Comment by ainthek** [comment]
+1
